export { default as Alert } from "./alert/alert";
export { default as FixedAlert } from "./fixed-alert/fixed-alert";
export { default as Loader } from "./loader/loader";
export { default as FixedOverlayLoader } from "./fixed-overlay-loader/fixed-overlay-loader";
export { default as Navbar } from "./navbar/navbar";
export { default as Pagination } from "./pagination/pagination";
export { default as Movie } from "./movie/movie";
export { default as ButtonIcon } from "./button-icon/button-icon";
export { default as FormGroup } from "./form-group/form-group";
